version: '3.9'

services:
    webapiclient2:
        image: ${DOCKER_REGISTRY-}webapiclient2
        build:
          context: .
          dockerfile: WebAPIClient2/Dockerfile
        network_mode: host  
        
    
    schild:
        image: ${DOCKER_REGISTRY-}schild
        build:
          context: .
          dockerfile: schild/Dockerfile
        network_mode: host

    